name: tudo_no_tabuleiro_app
description: A new Flutter project.

version: 1.0.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get: ^3.26.0
  
  ### Plugins Firebase ###
  firebase_core: ^1.0.0
  firebase_core_platform_interface: ^4.0.0
  firebase_messaging_platform_interface: ^2.0.0
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  ### Plugins Firebase ###

  google_sign_in: ^4.5.3
  auto_size_text: ^2.1.0
  carousel_slider: ^2.2.1
  cached_network_image: ^3.0.0-nullsafety
  flutter_icons:
  fluttertoast:
  url_launcher:
  map_launcher: ^0.12.2
  flutter_staggered_grid_view: ^0.3.2
  pinch_zoom_image_last: ^0.3.1
  #awesome_notifications: ^0.0.5+7
  flutter_launcher_icons: ^0.9.0
  flutter_image_compress: ^0.7.0
  supercharged: ^1.11.0
  uni_links: ^0.4.0
  image_picker: ^0.7.2
  google_maps_flutter: ^2.0.1
  location: ^4.0.2
  shared_preferences: ^2.0.3
  maps_toolkit: ^1.1.0+2
  path_provider: ^2.0.1
  flutter_local_notifications: ^5.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/imoveis.png
    - assets/images/divulgacao.png
    - assets/images/emprego.png
    - assets/images/achados-perdidos.png
    - assets/icon/splashscreen.png